[pytest]
pythonpath = .
markers =
    smoke: базовые проверки открытия и основных элементов
    auth: тесты авторизации/регистрации
    validation: тесты валидации форм
base_url = https://test-mrn.astondevs.ru
